upload boot image to artifacts

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,14 +17,13 @@ jobs:
         run: |
           sudo apt update
           sudo apt install -y android-sdk-libsparse-utils bmap-tools debootstrap qemu-user-static rsync systemd-container gnupg dirmngr
-          
-          echo "Adding Mobian GPG key..."
-          gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 951D61F2BC232697 || { echo "Failed to fetch key from keyserver. Proceeding to next step (optional)."; }
+
+          gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 951D61F2BC232697 || { echo "Failed to fetch key from keyserver..."; }
           gpg --export 951D61F2BC232697 | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/mobian-archive-keyring.gpg
           
           sudo apt update
 
-      - name: Cache Nethunter Base Image (base.tgz)
+      - name: Restore or Cache Nethunter Base Image
         id: cache-base
         uses: actions/cache@v4
         with:
@@ -40,6 +39,8 @@ jobs:
       - name: ⬆️ Upload Nethunter Image Artifact
         uses: actions/upload-artifact@v4
         with:
-          path: 'kali_phosh_nothingphone1_*.img'
+          path: |
+            kali_phosh_nothingphone1_*.img
+            boot_spacewar_*.img
           name: 'nothingphone1-nethunter-image'
           retention-days: 7
